def bantuan(role):
    if (role=="admin"): #print semua fungsi
        print("===================================HELP===================================")
        print("register - registrasi akun baru")
        print("carirarity - mencari gadget berdasarkan rarity")
        print("caritahun - mencari gadget berdasarkan tahun ditemukannya")
        print("tambahitem - menambah item ke inventori sistem")
        print("hapusitem - menghapus item  dari database")
        print("ubahjumlah - mengubah jumlah gadget dan consumable yang ada dalam sistem")
        #print("riwayatpinjam - melihat history peminjaman gadget")
        #print("riwayatkembali - melihat history pengembalian gadget")
        #print("riwayatambil - melihat history pengambilan consumable")
        print("save - menyimpan data yang berubah")
        print("help - menampilkan command list")
        print("exit - keluar dari sistem")
    else:
        print("===================================HELP===================================")
        print("carirarity - mencari gadget berdasarkan rarity")
        print("caritahun - mencari gadget berdasarkan tahun ditemukannya")
        print("pinjam - meminjam gadget dari inventory sistem")
        print("kembalikan - mengembalikan gadget yang dipinjam")
        print("minta - meminta consumable dari inventory sistem")
        print("gacha - consumable gambling")
        print("save - menyimpan data yang berubah")
        print("help - menampilkan command list")
        print("exit - keluar dari sistem")